name: CI

on: [push, pull_request]

jobs:
  compile_lint_and_tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install
        run: yarn
      - name: TSC compile
        run: yarn tsc
      - name: TSC compile E2E
        run: yarn tsc:e2e
      - name: Lint
        run: yarn lint
      - name: Tests
        run: yarn test
      - name: E2E Tests
        run: yarn test:e2e:ci
